export default {
  // images
  // networkError: require('../assets/images/networkError/networkError.png'),
  // loadMoreError: require('../assets/images/loadMoreError/loadMoreError.png'),
  // emptyImagePlaceholder: require('../assets/images/emptyImagePlaceholder/emptyImagePlaceholder.png'),
  // alert: require('../assets/images/alert/alert.png'),
  // // temp/dummy images
  // burger: require('../assets/images/burger/burger.png'),
  // cookHouse: require('../assets/images/cookHouse/cookHouse.jpg'),
  // tinyHome: require('../assets/images/tinyHome/tinyHome.jpg'),
  // host: require('../assets/images/host/host.jpg'),
  // tab images
  // drawer images
  // gif images

  lottie: {
    splash: require('../assets/lottie/lottie.json'),
    splashImg: require('../assets/lottie/Splash.png'),
  },
  tab: {
    homeIcon: require('../assets/icon/homeIcon/home.png'),
  },
  icon: {
    talentonLogo: require('../assets/icon/talentonLogo.png'),
    Aviation: require('../assets/icon/Aviation.png'),
    Hospitality: require('../assets/icon/Hospitiality.png'),
    Finance: require('../assets/icon/Finance.png'),
    Yatching: require('../assets/icon/Yatching.png'),
    Assistant: require('../assets/icon/Assistant.png'),
    Plus: require('../assets/icon/plus.png'),
    Management: require('../assets/icon/Management.png'),
    Pic: require('../assets/icon/PIC.png'),
    Sic: require('../assets/icon/SIC.png'),
    FlightAttendant: require('../assets/icon/FlightAttendant.png'),
    Engineering: require('../assets/icon/Engineering.png'),
    Finance1: require('../assets/icon/Finance1.png'),
    PlusBold: require('../assets/icon/Plus1.png'),
    Calender: require('../assets/icon/calendar.png'),
    talentonLogo: require('../assets/icon/talentonLogo.png'),
    Whatsapp: require('../assets/icon/Whatsapp.png'),
    Email: require('../assets/icon/Email.png'),
    MinusBold: require('../assets/icon/MinusBold.png'),
    PlusSquare: require('../assets/icon/PlusSquare.png'),
    iconPlus: require('../assets/icon/iconPlus.png'),
    arrowDropdownCircle: require('../assets/icon/arrowDropdownCircle.png'),
    close: require('../assets/icon/close.png'),
    tick: require('../assets/icon/tick.png'),
    cross: require('../assets/icon/cross.png'),
    video: require('../assets/icon/video.png'),
    thinkFace: require('../assets/icon/thinkFace.png'),
    stars: require('../assets/icon/stars.png'),
    info: require('../assets/icon/info.png'),
    X: require('../assets/icon/X.png'),
    upHand: require('../assets/icon/upHand.png'),
    rightHand: require('../assets/icon/rightHand.png'),
    leftHand: require('../assets/icon/leftHand.png'),
    like: require('../assets/icon/like.png'),
    bellIcon: require('../assets/icon/bellIcon.png'),
    delete: require('../assets/icon/delete.png'),
    bin: require('../assets/icon/bin.png'),
    Edit: require('../assets/icon/Edit.png'),
    phone: require('../assets/icon/phone.png'),
    settings: require('../assets/icon/settings.png'),
    copy: require('../assets/icon/copy.png'),
    clock: require('../assets/icon/clock.png'),
    img: require('../assets/icon/img.png'),
    img1: require('../assets/icon/img1.png'),
    img2: require('../assets/icon/img2.png'),
    img3: require('../assets/icon/img3.png'),
    img4: require('../assets/icon/img4.png'),
    img5: require('../assets/icon/img5.png'),
    reset: require('../assets/icon/reset.png'),
    Face: require('../assets/icon/Face.png'),
  },
  images: {
    appBg: require('../assets/images/Background.jpg'),
    headerIcon: require('../assets/images/headerIcon.png'),
    picture: require('../assets/images/picture.png'),
    picture1: require('../assets/images/picture1.png'),
    CV: require('../assets/images/Cv.png'),
  },
  useriamge: {
    user1: require('../assets/userImage/clint2.png'),
    user2: require('../assets/userImage/clint3.png'),
    user3: require('../assets/userImage/clint4.png'),
    user4: require('../assets/userImage/pilotimage.png'),
    user5: require('../assets/userImage/profile1.jpg'),
    user6: require('../assets/userImage/profile2.jpg'),
  },
  cv: {
    CVImages: require('../assets/images/CVImages/CVImages.png'),
    StarsImages: require('../assets/images/starImages/starImages.png'),
    ContractImage: require('../assets/images/ContractImage/ContractImage.png'),
  },
  menuicon: {
    position: require('../assets/images/documentIcon2/documentIcon2.png'),
    interview: require('../assets/images/interviewIcon/interviewIcon.png'),
    download: require('../assets/images/documentDownloadIcon/documentDownloadIcon.png'),
    hiring: require('../assets/images/hiringIcon/hiringIcon.png'),
    notepad: require('../assets/images/notepadIcon/notepadIcon.png'),
    contact: require('../assets/images/contectIcon/contectIcon.png'),
    star: require('../assets/images/starsIcon/starsIcon.png'),
  },
};
